language: java
jdk:
- openjdk8
services:
- docker

install:
- bash scripts/install.sh
script:
- mvn test
- bash scripts/build.sh rmspogfo
- docker build -t bwerquin/pogues-bo .
after_success:
- bash scripts/tag.sh
deploy:
  - skip_cleanup: true
    provider: script
    script:
      echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      && docker push bwerquin/pogues-bo
    on:
      branch: master
after_deploy:
- bash scripts/gitbook.sh
branches:
  except:
  - "/^v[0-9]+\\.[0-9]+\\.[0-9]+.*/"
